<?php

namespace apps\auth\schemas;

use phpbb\db\collection\entity;
use phpbb\db\collection\field;

class organisations extends entity
{
    public function __construct()
    {
        $this
            ->field('uuid', field::AUTOGENERATED, field::TYPE_UUID)
            ->field('type', 'group')
            ->field('name')
            ->field('description')
            ->field('creator', null, field::TYPE_UUID)
            ->index('uuid', field::INDEX_PRIMARY)
            ->reference('creator', users::class);
    }

    public function metadata($field, $value)
    {
        $this->metadata->$field = $value;
    }
}
