<?php

namespace apps\auth\schemas;

use phpbb\db\collection\entity;
use phpbb\db\collection\field;
use stdClass;

class users extends entity
{
    public function __construct()
    {
        $this
            ->field('uuid', field::AUTOGENERATED, field::TYPE_UUID)
            ->field('name')
            ->field('metadata', new stdClass, field::TYPE_OBJECT)
            ->index('uuid', field::INDEX_UNIQUE);
    }

    public function metadata($field, $value)
    {
        $this->metadata->$field = $value;
    }

    public function avatar($url)
    {
        $this->metadata('avatar', (object) [
            'url' => $url
        ]);
    }
}
