version: '3.1'
services:
  web:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./htdocs:/var/www/html
      - /var/www/vendor
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
    #  - ./data/mongodb:/data/db
      - ./tests/fixtures/mongodb/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongoui:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo