<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit15beafe2411e6f424902f184fc680861
{
    public static $files = array (
        'e39a8b23c42d4e1452234d762b03835a' => __DIR__ . '/..' . '/ramsey/uuid/src/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'phpbb\\' => 6,
        ),
        'a' => 
        array (
            'apps\\' => 5,
        ),
        'R' => 
        array (
            'Ramsey\\Uuid\\' => 12,
            'Ramsey\\Collection\\' => 18,
        ),
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
        'B' => 
        array (
            'Brick\\Math\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'phpbb\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/phpbb',
        ),
        'apps\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/apps',
        ),
        'Ramsey\\Uuid\\' => 
        array (
            0 => __DIR__ . '/..' . '/ramsey/uuid/src',
        ),
        'Ramsey\\Collection\\' => 
        array (
            0 => __DIR__ . '/..' . '/ramsey/collection/src',
        ),
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
        'Brick\\Math\\' => 
        array (
            0 => __DIR__ . '/..' . '/brick/math/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit15beafe2411e6f424902f184fc680861::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit15beafe2411e6f424902f184fc680861::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit15beafe2411e6f424902f184fc680861::$classMap;

        }, null, ClassLoader::class);
    }
}
